version: '3'

services:
  nginx:
    image: nginx:latest
    # монрируем лок дир ./ to remote dir
    volumes:
      - ./:/var/www/
      - ./__docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./__docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - 8000:80
    container_name: nginx-test_blog
    depends_on:
      - php-fpm

  php-fpm:
    user: "1000:1000"
    build:
      context: .
      dockerfile: __docker/app/Dockerfile
    environment:
      PHP_IDE_CONFIG: "serverName=shop"
    volumes:
      - ./:/var/www
      - ./__docker/app/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./__docker/app/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./__docker/app/php.ini:/usr/local/etc/php/conf.d/my-custom-php.ini
    container_name: php-fpm_test_blog
    depends_on:
      - mariadb


  mariadb:
    user: "1000:1000"
    image: mariadb:10
     # restart container always ( когда контейнер подает по какойто причне)
    volumes:
      - ./__docker/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: SuperUser
      MARIADB_USER: superuser
      MARIADB_PASSWORD: SuperUser
      MARIADB_DATABASE: news
    container_name: mariadb-test_news

